### ISSUE TITLE
Add support for displaying graphics

### ISSUE THREAD

**Issue by jonpalmisc** [jonpalmisc/Maui#1]
Functions like `Plot3D` currently cannot be used since the UI & engine wrapper do not support handling/displaying graphics.

**Comment by xusheng6** [comment]
<img width="585" alt="Screen Shot 2022-03-27 at 1 25 07 PM" src="https://user-images.githubusercontent.com/94503187/160268022-d0f94a57-da1f-4d74-8ed2-6deb7a09c446.png">

I tried to run a command that generates graphical output, but the result is just `-Graphics-` in text. I am not sure how we should tell the engine to return the actual graphics to us. 

The same behavior is observed if we use MMA's own command line front-end. That is expected, though, because it would be unable to display graphics anyways.

**Comment by xusheng6** [comment]
On the other hand, in http://edenwaith.com/development/tutorials/mathlink/ML_Tut.pdf we see that there is a `DisplayPacket` that marks the start of PostScript output.

**Comment by xusheng6** [comment]
I think we can do it in this way: whenever we see the output string is `-Graphics-`, we run an additional command that exports the graphics to a JPEG, e.g., Export["/tmp/abc.jpg", %], and then display the exported image file.

**Comment by xusheng6** [comment]
Initial support is added in https://github.com/jonpalmisc/Maui/commit/1a10d162dedd1fb62083af898f8ed3f43713f9fe
